### ISSUE TITLE
What material to use?

### ISSUE THREAD

**Issue by rvanginneken** [egladman/hhkb-usb-cover#4]
Hey egladman,

I'm about to send this to a 3D printer, but I'm wondering what material you'd advise to use? Currently I'm looking at "rubber-like".

Also, can you give some info how snug it will fit? I'm using the board on different places and the covers need to stay in place. They should be removable somehow tho, to get to the reset button.

Looking forward to your feedback!

**Comment by egladman** [comment]
I've had success printing the covers in abs and pla. The covers fit like a glove, to remove them you must open up your hhkb and pop them out from the other side.

**Comment by rvanginneken** [comment]
Thanks for the info!
I wasn't aware that the reset button is behind the already removable slide cover, so it's perfect if they "fit like a glove". :)

I asked a friend with a home printer to print them for me, ordering them was getting a bit expensive in total. I'll update when I get them.

**Comment by tengg** [comment]
I used PLA 100 micron, but it breaks when plugin.
What resolution do you use?

**Comment by egladman** [comment]
That's unfortunate :worried:. I print at 200. PLA is known to be brittle, however I haven't experienced any issues on my end.

**Comment by tengg** [comment]
The print I have probably not from a very good 3d printer.
Do you know which material is more durable? ABS?

**Comment by egladman** [comment]
I mean ABS is technically more durable. The issue with ABS is that prints sometimes warp due to the heat from the bed.
